#!/usr/bin/env bash

echo -n "Unused exports: "
UNUSED=`yarn --silent yarn ts-prune | grep -v 'ts-prune' | grep -v 'used in module'`
if [ -z "$UNUSED" ]
then
  echo "0"

  exit 0
else
  UNUSED_COUNT=`echo "${UNUSED}"| wc -l | tr -d '[:space:]'`
  echo "${UNUSED_COUNT}"
  echo ""
  echo "${UNUSED}"
  echo ""

  exit 1
fi
